### ISSUE TITLE
Function that returns everything!

### ISSUE THREAD

**Issue by alizat** [Dainanahan/dbparser#1]
Add a function, e.g. parse_everything(), that parses all the data and returns the parsed data in the form of a list of dataframes.

Note that if save_table=TRUE, all the parsed data should be successfully get saved in the DB.

**Comment by alizat** [comment]
What is the name of the new function that parses and returns everything?

**Comment by MohammedFCIS** [comment]
@alizat you can get this info from the commit in the issue 😉
