### ISSUE TITLE
Review package returned data against drugbank site

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#15]

**Comment by alizat** [comment]
For the most part, the data in the database XML file is mostly available in the DrugBank website and vice versa (with very few exceptions). However, some of the titles are not the same. For example, the data under the "Taxonomy" section on the DrugBank website is found under the "<classifications>" tag inside the XML file. It is no big deal, but it is something to bear in mind while designing the UI for dbbrowser (which of the different titles should we use?).

For our intents and purposes, I find that the dbparser package parses the DrugBank database info nicely and comprehensively.
