### ISSUE TITLE
Add Parsed Data to Kaggle as a Contributed Dataset

### ISSUE THREAD

**Issue by alizat** [Dainanahan/dbparser#30]
Gather all the data frames that are returned by dbparser's `parse_drug_all()` function, and submit to Kaggle as a dataset. This dataset is to be updated quarterly with each new release of the DrugBank dataset.

**Prerequisites:**
- Ask permission from DrugBank and make sure it is okay to do such a thing.
- Homework: Can we contribute the dataset as a team (Dainanahan)?
- Challenge: The DrugBank data is >1GB in size. How to upload such a dataset?
    - Suggested Solution: Rent an online VM for a day. From that VM, download and parse DrugBank XML, then upload to Kaggle.
- The dbparser website has to be *finalized*.
    - Meaning of the word, 'finalized', to be discussed and specified later, but I am mainly referring to tutorials, usage examples, blogs and inspiration from our previously submitted DataCamp proposal.
- Prior to contributing the dataset, there needs to be enough tutorial/blog material for Kagglers to know what to do with the data (what analyses to perform? what interesting questions could be answered with the dataset? perhaps contribute a Kaggle kernel of our own immediately after the dataset is posted online? etc.)
- Homework: We have to make sure that the names of the variables (columns) of the data frames (returned by dbparser) are acceptable and in the way that we want them (i.e. self-explanatory without much needed elaboration from our side).
    - This will require a good look at the data frames' column names.
    - The `parent_key` variable in particular will be revisited (e.g. wherever `parent_key` refers to a drug, change column name to `drugbank_id`?).

**Comment by alizat** [comment]
For reasons pertaining to branding, it is preferable that the Kaggle dataset be uploaded AFTER most (if not all) the other dbparser issues have been resolved.

Furthermore, these are extra features that nice to have for this dataset:
* The dataset to automatically update itself regularly
* See of there is a stable pattern on drugbank release dates
    * Make use of said pattern
    * If there is no pattern  -->  update once a month
* On the overview page of this dataset on Kaggle, tell people to give us feedback on dbparser, and if there are more features they wish to add (encourage to add issues/leave comments)

**Comment by MohammedFCIS** [comment]
> For reasons pertaining to branding, it is preferable that the Kaggle dataset be uploaded AFTER most (if not all) the other dbparser issues have been resolved.
> 
> Furthermore, these are extra features that nice to have for this dataset:
> 
> * The dataset to automatically update itself regularly
> * See if there is a stable pattern for DrugBank release dates
>   
>   * Make use of said pattern
>   * If there is no pattern  -->  update once a month
> * On the overview page of this dataset on Kaggle, tell people to give us feedback on dbparser, and if there are more features they wish to add (encourage to add issues/leave comments)
a separate R dataset package will be created for that
