### ISSUE TITLE
Remove *Count* features from drug data set

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#35]
**Is your feature request related to a problem? Please describe.**
These features has no use currently as they will be replaced by drugQuery package

**Describe the solution you'd like**
New package called drugQuery will replace these features and provide more complex and advanced queries on drug bank

**Comment by alizat** [comment]
Bear in mind that there is another issue (#33) regarding these count variables. If you end up removing the count variables do not forget to close that other issue as well.
