### ISSUE TITLE
Datasets Features Names 

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#38]
**Is your feature request related to a problem? Please describe.**
When I used the generated dataframes from dbparser I had to rename its features to be displayed properly 

**Describe the solution you'd like**
Rename features like *text* with a proper name, features with small caps to be Camel case

**Comment by alizat** [comment]
I am under the impression that, instead of Camel case, it would better to add underscores between the different words in the feature name (e.g. `gene_ontology` is better than `geneOntology`). To be discussed.
