### ISSUE TITLE
complete current documentation

### ISSUE THREAD

**Issue by MohammedFCIS** [Dainanahan/dbparser#6]

**Comment by alizat** [comment]
Finished the vignette for the most part. What remains is the following:
- Complete the section in the vignette on *## Saving into a database*
- When a knitr document is produced (using Ctrl+Shift+K), the figures are _small_ and _aligned left_.
    - Figures are to be normal-sized and centered. This may be related to vignettes not supporting **retina** figures. Side Note: I do not know what retina figures mean. I just know vignettes don't support them :)
